import Dashboard from "../components/Dashboard";
import Sidebar from "../components/Sidebar";
import Head from "next/head";

const DashboardPage = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: "flex" }}>
        <Sidebar />
        <Dashboard />
      </div>
    </>
  );
};

export default DashboardPage;
